on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:
name: Test
jobs:
  test:
    name: ${{ matrix.os }} on node ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: git config --global user.email "hi@koddsson.com"
      - run: git config --global user.name "Kristján Oddsson"
      - run: yarn run test
